name: Terraform Deployment to AKS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Deploy AKS Infrastructure'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./aks

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./aks

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./aks

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./aks
